[package]
name = "mtk_cli"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "mtk"
path = "src/main.rs"

[dependencies]
mtk = { path = "../mtk" }
clap = { version = "4.5.39", features = ["derive"] }
serde_json = "1.0.140"
url = "2.5"
